version: 0.1.{build}-{branch}
skip_tags: false
skip_non_tags: false
max_jobs: 1

image: Visual Studio 2015
init:
  - git config --global core.autocrlf true
clone_depth: 1
platform:
  - Win32
  - x64
configuration:
  - Release
before_build:
  - mkdir build
  - cd build
  - 'cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DCMAKE_INSTALL_PREFIX=. ..'
build_script:
  - 'msbuild /p:configuration=%CONFIGURATION% ALL_BUILD.vcxproj'
  - 'msbuild /p:configuration=%CONFIGURATION% src/app/INSTALL.vcxproj'

test_script:
  - ctest
after_test:
  - 'if "%PLATFORM%" == "Win32" set PLATFORM=x86'
  - 'set ARCHIVE_NAME=fifa2018-%APPVEYOR_REPO_BRANCH%-windows-%PLATFORM%.zip'
  - '7z a %ARCHIVE_NAME% fifa2018'

artifacts:
  - path: build/${ARCHIVE_NAME}
    name: fifa2018
    type: zip

deploy:
  - provider: GitHub
    release: ${APPVEYOR_REPO_BRANCH}
    description: 'World Cup 2018 Simulation'
    auth_token:
      secure: wCLCNSQ1gr1PWkBxxhfkeTdWCjdmChy3C/yl0w0iYCB6OThAnJZWUHL442xj77yd
    artifact: fifa2018
    draft: false
    prerelease: false
    on:
      branch: /v\d+\.\d+\.\d+/
      appveyor_repo_tag: true
